### PR TITLE
New: member.Relationship model, combining referents and emergency contacts. Closes #740

### LINKED ISSUE #740: Multiple related persons combining emergency contacts and referents
(As requested by and discussed with Jean-François on 2017-05-12, multiple referents are essential. This is a solution that minimizes changes such that we can finish milestone 1.1 ASAP)

(EDITED by @lamontfr 2017-05-20 19:12 EDT)
### Expected Behaviour
- For each instance of a "Related person" the attributes will be displayed as follows in the second block of Client / Information / Personal with block title = Related Persons :
  - First name / Prénom (required)
  - Last name  / Nom (required)
  - Nature of relationship / Lien de relation (required, free text) (ex. Doctor, Friend, Gov. official, Daughter)
  - Home Phone / Téléphone maison (optional)
  - Cell. Phone / Téléphone cellulaire (optional)
  - Emergency Contact / Contact d'urgence : [x] (checked if YES)
  - Referent / Référent : [x] (checked if YES)
  - Workplace information / Lieu de travail (required if referent checked, otherwise empty)
  - Referral Date / Date du référencement  (required if referent checked, otherwise empty)
  - Referral reason / Raison du référencement  (required if referent checked, otherwise empty)
  - Remark / Remarque (optional, used by staff)
- We may have none or many "Related persons" for a client.
- A member may simultaneously be a referent and an emergency contact.
- A member may be a related person but neither a referent nor an emergency contact.
- There is no requirement to supply an EmergencyContact (or a referent) in the new
 client wizard.

### Actual Behaviour
- Can only have one referent per client.
- Emergency contact is compulsory

### Revised suggestion to solve issue (based on comments)
- Create a new model Relationship and remove models Referencing and EmergencyContact and move data from the two latter to the former.
- Relationship would be : 
```python
class Relationship(models.Model):
    member = models.ForeignKey('member.Member')
    client = models.ForeignKey('member.Client')
    nature = models.CharField(max_length=100)
    type = JSONField()
    extra_fields = JSONField()
    remark = models.TextField()
```
- field "type" is a multiple choice : none, one or many of ('referent', 'emergency').
- when 'referent' is in field "type", extra_fields are : referral_date, referral_reason.
- In the UI use a new label "Related Persons" instead of "Emergency Contacts"
- Use the Django migration module to : 
  - Copy Referencing data into Relationship, including extra Referents migrated from Feast that does not show in the UI.
  - Copy EmergencyContact data into Relationship.
- In the UI remove Referent
- We dot not plan to run the data migration from Feast to Souschef again. Jean-François told me that they try to continously update the client data in Souschef (but not the orders). When we put milestone 1.1 in production they will run in parallel with Feast and manually adjust the discrepancies.

### PR DESCRIPTION
**Pull request by lingxiaoyang**
### Changes proposed in this pull request:

* Model change: adding `member.Relationship`, deleting `member.Referencing` and `member.EmergencyContact`. Migration `member.0032` is provided to take care of existing database.
* Forms: creating relationship formsets based on emergency contact formsets. Deleting referent form and emergency contact formsets.
* Views and templates: removing referent and emergency contacts from client form wizard. Inserting relationships after address information and before payment information in the wizard.
* Admin: replacing referent and emergency contacts with relationships.
* UI: adding dynamic fields in relationship form to support the extra fields of a referent relationship.
* Unit test: replacing referent and emergency contacts with relationships. Testing the forward and reverse migration of `member.0032`. Fixing a problem in migration test case that causes errors when there are multiple migration unit tests.
* Sample data fixture: replacing referent and emergency contacts with relationships.

### Status

- [x] READY
- [ ] HOLD
- [ ] WIP (Work-In-Progress)

### How to verify this change

1. `python3 manage.py migrate`. This should work fine and should transfer all old data into new relationship model.
2. Go to Admin -> Relationships to verify transferred relationship entries. They are also available in Client detail view as inline formsets.
3. Go to client information view to check the display of relationship entries.
4. Try editing the relationships of an existing client.
5. Try creating the relationships of a new client.

### Deployment notes and migration

- [x] Migration is needed for this change

### New translatable strings

- [x] If applicable, I have included updated .po files with new strings (see https://github.com/savoirfairelinux/sous-chef/blob/dev/docs/internationalization.adoc)

### Additional notes

Needs more manual tests.

### CODE REVIEW

**Comment by lamontfr** [comment]
@lingxiaoyang You did a big job, thank you ! I started testing and here is what I have found so far : 

1- The migration worked OK.
2- The admin is OK.
3- The display in http://localhost:8000/member/view/916/information is OK.
4- There are some bugs when I EDIT the relationships for a client : 
4.1- For a referrent, in the edit view http://localhost:8000/member/916/update/relationships/ the referral date and reason do not show until I uncheck/check the referrent (or emergency) checkbox
4.2- When I type data in the Remark field, it is not saved in the DB. However the nature and the type are saved correctly.
4.3- When I add a relationship for which I do not check the referrent type when I click save, the UI gives missing referral date and reason error because it has checked the referrent type by itself. If I uncheck it and save again, it works (but there is another bug, see 4.4).
4.3- When I add a new relationship, it replaces the last one. I have two relationships (John and Paul), I add data for a third one (Mary), I click save, if the new one is a referrent I get no error (otherwise see 4.3) but then it displays only two (John and Mary).

**Comment by lingxiaoyang** [comment]
@lamontfr  Thank you for the feedback and testing! I'll verify and correct them.

> 4.1- For a referrent, in the edit view http://localhost:8000/member/916/update/relationships/ the referral date and reason do not show until I uncheck/check the referrent (or emergency) checkbox

Did you rerun `gulp`? I changed some frontend code.

You'll also see 'Work Information' field inside 'Create new member' form, when selecting Referent.

**Comment by lingxiaoyang** [comment]
@lamontfr  Fixed in da85e0d. Mostly they were caused by frontend problems... Could you check again?

**Comment by lamontfr** [comment]
@lingxiaoyang Thanks for the corrections. I had run `gulp` before starting to test yesterday. I will retry later today.

**Comment by lamontfr** [comment]
@lingxiaoyang I pulled this PR again, I reran gulp and cleared the browser cache. Here are the results of my tests : 
1- The migration was already done.

2- The admin is OK except : 
2.1- For a client, there are five inline formsets for relationships. When we change some data for the client (for example the alert field) we cannot save because empty relationship formsets have required fields. BUG. I suggest adding extra : 
```python
class RelationshipInline(admin.TabularInline):
    model = Relationship
    extra = 0
```
But if the single relationship is not a referent, the admin still complains about required fields. BUG.

3- The display in http://localhost:8000/member/view/916/information is OK.

4- Edit a relationship is OK except : 
4-1 For a referrent, in the edit view http://localhost:8000/member/916/update/relationships/ the referral date and reason do not show until I uncheck/check the referrent (or emergency) checkbox. BUG.

5- Create a new client and his(her) relationship(s), including entering work information for a new member, is OK except : 
5.1- At least one relationship must be created for a client. This does not match the expected behavior of issue #752. UNSATISFIED REQUIREMENT. I tried to delete all relationships of an existing client in the admin and the pages http://localhost:8000/member/view/921/information and http://localhost:8000/member/921/update/relationships/ display "empty" correctly. I can then add the first relationship in http://localhost:8000/member/921/update/relationships/ and save it.

That's it for now.

**Comment by lingxiaoyang** [comment]
@lamontfr Thank you for the detailed feedback! 


Here's the updated version in 8eff5fb. Changes:

2.1 -- `extra=0` worked perfectly, thank you! I added `blank=True` on the model fields so that empty JSON list and object are allowed by Django admin.

4.1 -- There was perhaps browser inconsistency. I rewrote the initialization of hide/show from JS code to Django template code and it should be fine now.

5.1 -- Fixed! Please test further to see if there are edge cases that I didn't test.

**Comment by lamontfr** [comment]
@lingxiaoyang Thank you Ling, I will test tonight.

**Comment by lingxiaoyang** [comment]
@lamontfr  Thank you for reviewing!

**Pull request merged**
