### PR TITLE
Fix #558 -- Add filters on the review orders page

### LINKED ISSUE #558: Kitchen Count: add filters on the review orders page
### Expected Behaviour

In the first step of the Kitchen Count, the user should be able to filter by clients. An input text should be present.

### Actual Behaviour

No filters at all on the page.

capture d ecran de 2016-12-08 14-49-08

### Steps to reproduce

* Click on the Kitchen Count menu item
* Click on **Generate Orders** (make sure to have the fixtures loaded before)

### PR DESCRIPTION
**Pull request by ellmetha**
### Changes proposed in this pull request:

* Add a new filter class and use it in order to filter the orders in the "Kitchen Count" section

### Status

- [X] READY
- [ ] HOLD
- [ ] WIP (Work-In-Progress)

### How to verify this change

* Go to the "Kitchen Count" section and enter a client name in the related form field

### CODE REVIEW

**Comment by lingxiaoyang** [comment]
@ellmetha  The button "OK, I'm ready" is sometimes misplaced: 

image
image

**Comment by lingxiaoyang** [comment]
@ellmetha   After clicking on "Generate Orders", there's a blank row in the table:

image

**Comment by ellmetha** [comment]
@lingxiaoyang I don't think that those issues are related with the changes provided in this PR. Perhaps we should create new issues related to what you are pointing out. But I can fix them in the current branch too.

**Comment by lingxiaoyang** [comment]
@ellmetha  I'm okay with either one.

**Comment by manumilou** [comment]
I don't think these problems occur in the dev branch. They should be fixed in this PR.

**Comment by ellmetha** [comment]
@manumilou they are fixed with the latest commit. ;)

**Pull request merged**
