### PR TITLE
Replacement of Aaboffill dev 653 (Fixes #653)

### LINKED ISSUE #653: Handle Multiple emergency contacts
### Expected Behaviour

A client should be able to have multiple emergency contacts attached to him. The creation/edition form must allow multiple selection, and the client's view should show all related contacts.

### Actual Behaviour

Only one contact is supported per client.

### Steps to reproduce

* Find a client with multiple emergency contacts 
* Edit client 
* Click emergency tabs 
* ...

see screenshot 
multipleemergencycontact

### PR DESCRIPTION
**Pull request by lingxiaoyang**
### Changes proposed in this pull request:

On top of what @aaboffill has done:
* New unit tests for this database migration.

### Status

- [x] READY
- [ ] HOLD
- [ ] WIP (Work-In-Progress)

### How to verify this change

See PR #664 

### Deployment notes and migration

- [x] Migration is needed for this change

### New translatable strings

- [x] If applicable, I have included updated .po files with new strings (see http://goo.gl/kfBO7N)

### Additional notes

See #664

### CODE REVIEW

**Comment by lingxiaoyang** [comment]
@erozqba  You can review this now.

**Comment by erozqba** [comment]
@manumilou I think this is ready to merge! Can you test it with production data and validate that everything is OK after the migration?

**Comment by manumilou** [comment]
@erozqba We really need to find another way to test those changes with large sets of dummy data, close from production data. Otherwise, I'll keep being the bottleneck in this pipeline. What do you need to make sure your changes won't impact production ? @lingxiaoyang Same question.

**Comment by lingxiaoyang** [comment]
@manumilou  So it'll not be a unit test. I would say the only way is to backup production database, monitor how the migration goes, and compare the data...

**Comment by lingxiaoyang** [comment]
@erozqba We're merging this PR based on your approval. The problem that we have discussed should be readdressed during the next deployment. For merging it into develop branch, the unit test is enough. (ref @manumilou)

**Pull request merged**
