### PR TITLE
New: route size monitoring on dashboard. Closes #713.

### LINKED ISSUE #713: Route size monitoring - Dashboard request
### Expected Behaviour

When asked whether or not we can accept a new client on any given route, we need to know:

1# the nb. of episodic meals that could be ordered (if all of them ordered on the same day)
 per route.  (adding up meal defaults numbers from all active, paused and pending episodic clients and choosing the biggest number of meals if a client receives different meal quantity on different days)  

2# the nb. of ongoing meals scheduled per route per day. (adding up meal defaults numbers from all active, paused and pending ongoing clients)  

This would take the form of a table. 

````
                       Episodic   *   Mon   Tue   Wed   *   Fri   Sat
CDN       
Centre-Sud
Centre-Ville
Mile-End
McGIll
NDG
Westmount
````

### Actual Behaviour

nothing

### Steps to reproduce

* step 1
* step 2
* ...

### PR DESCRIPTION
**Pull request by lingxiaoyang**
### Changes proposed in this pull request:

* Added route size monitoring table on dashboard:
image 
* The calculation is properly optimised: (I left a duplicate there as it'll need more magic to eliminate it, which may decrease readability. If needed, I can go further.)
capture du 2017-05-04 10-47-18
* Unit test.

### Status

- [x] READY
- [ ] HOLD
- [ ] WIP (Work-In-Progress)

### How to verify this change

Verify if the numbers match existing data.

### Deployment notes and migration

- [x] Migration is needed for this change

### New translatable strings

- [x] If applicable, I have included updated .po files with new strings (see https://github.com/savoirfairelinux/sous-chef/blob/dev/docs/internationalization.adoc)

### Additional notes

none

### CODE REVIEW

**Comment by lamontfr** [comment]
@lingxiaoyang I verified this, the layout is good and the calculations are correct. I suggest that we slightly modify the tooltip as follows : 

**/src/page/templates/pages/home.html L73 BEFORE : **

```html
      <div class="ui segment">
        {% trans 'An overview of the number of main dishes delivered on each route. All active, paused and pending clients are taken into account. Format: "ongoing dishes (+ episodic dishes)"' as route_help_text %}
        <h3 class="ui blue header">{% trans "Route Size Monitoring" %}<small><i class="help-text question grey icon link" data-content="{{ route_help_text|force_escape }}"></i></small></h3>
      </div>
```
**/src/page/templates/pages/home.html L73 AFTER :  **

```html
      <div class="ui segment">
        {% trans 'An overview of the number of main dishes delivered on each route. All active, paused and pending clients are taken into account. Format: "ongoing scheduled dishes (+ episodic and ongoing unscheduled default dishes)"' as route_help_text %}
        <h3 class="ui blue header">{% trans "Route Size Monitoring" %}<small><i class="help-text question grey icon link" data-content="{{ route_help_text|force_escape }}"></i></small></h3>
      </div>
```

Do you want me to make the change in the html and .po files or do you prefer to do it yourself ?

**Comment by lingxiaoyang** [comment]
@lamontfr Updated. Thank you!

**Comment by lamontfr** [comment]
@lingxiaoyang I tested again and the tooltip is now perfect. Do you want me to merge the PR in dev ? I have not merged a PR before, but I think it will be a useful experience for me. Here are the steps that I plan to use from my project directory : 

```text
git checkout dev
git fetch upstream
git merge upstream/dev
git merge --no-ff lingxiaoyang-fix_713
git push origin dev
```
Is there anything else that I should do, like entering a commit message ?

**Comment by lingxiaoyang** [comment]
@lamontfr  Thank you! I think you have the write permission to sous-chef so that you can merge. 

The commands seem fine to me. In the last step, you may want to add `git push upstream dev` to update this repo also. 

We are not so strict on commit messages. So don't worry!

**Pull request merged**
