### PR TITLE
Fixed #717: Enhance client scheduled status change

### LINKED ISSUE #717: Enhance client scheduled status change UI
### Expected Behaviour

Wrote by JF in #685:

> Within the UI, we should be able to:
> 1# Cancel a future scheduled status change (i.e. client calls to cancel his planned vacation due to family emergency)
> 2# Cancel a current (ongoing) scheduled status change (client changes his mind in the middle of a meal delivery pause)
> 3# Lengthen a current (ongoing) scheduled status change (ie. prolonged hospitalisation)
> 4# Shorten a current (ongoing) scheduled status change (i.e Client is released from jail early for good conduct)
> 5# Lengthen a future scheduled status change
> 6# Shorten a future scheduled status change

This enhancement could easily bring confusion if simply added to the UI, because the scheduled changes are related with a client's actual status and vice versa. Needs discussion on how we define the backend behaviours.

### Actual Behaviour

Not implemented yet.

### Steps to reproduce

N/A

### PR DESCRIPTION
**Pull request by lingxiaoyang**
### Changes proposed in this pull request:

* Enhancement: display the upcoming change.
  * Case 1:
image
  * Case 2:
image
  * Case 3: There is be a warning state if the operation status is "error" or is still "to be processed" with a change date of today or before:
image

* New functionality: cancel this upcoming change. After prompting the user, deletes the displayed upcoming change.
image
image

* New functionality: reschedule this upcoming change. The same status change form is prompted, but pre-filled with the information of this upcoming change (status to, reason, change date and optional end date). Upon confirmation, the schedule will be replaced.
image
image
image
image

* Removed functionality: the "delete" button on scheduled status modifications list. 
* New: in Django admin, ClientScheduledStatus model is added.
* Removed: `NOT NULL` constraint on `Note` model. A null value should be considered "default" category or priority, because the PK=1 category or priority object may not exist in database and there's no way to readd it (the PK will only increase).

### Status

- [x] READY
- [ ] HOLD
- [ ] WIP (Work-In-Progress)

### How to verify this change

See above.

### Deployment notes and migration

- [x] Migration is needed for this change

### New translatable strings

- [x] If applicable, I have included updated .po files with new strings (see https://github.com/savoirfairelinux/sous-chef/blob/dev/docs/internationalization.adoc)

### Additional notes

none

### CODE REVIEW

**Comment by lingxiaoyang** [comment]
Removed "WIP" flag. Unit tests and translatable strings are added.

**Comment by erozqba** [comment]
@lingxiaoyang could you resolve the conflicts, please? Thanks in advance.

**Comment by lingxiaoyang** [comment]
@erozqba  Thank you! I didn't notice that..

**Comment by lingxiaoyang** [comment]
@erozqba  OK!

**Comment by lamontfr** [comment]
@lingxiaoyang I tested all the cases and it works perfectly. Thanks Ling for this excellent work ! You can now merge this PR.

**Comment by lingxiaoyang** [comment]
@lamontfr  Thank you! I rebased in acda830. I'm merging it now.

**Pull request merged**
