### PR TITLE
Fixed #610: support walking/driving/cycling in leaflet routing js

### LINKED ISSUE #610: Allow selecting a transport type for the routing machine
### Expected Behaviour

Leaflet.js routine machine can use different transport type (Bike, Walk, Car) when computing the itinerary. It should be customizable from the _Organize Route_ view, and be reflected on the routes list.

### Actual Behaviour

Every itinerary are computed with the **Biking** preset. 

### Steps to reproduce

* Go through the Kitchen count process
* Make sure that for a given route, every client is properly geolocalized
* Organize this route

### PR DESCRIPTION
**Pull request by lingxiaoyang**
### Changes proposed in this pull request:

* Add three vehicle buttons on leaflet routing interface. Uses Semantic UI basic button group.

image

* Refactor the related JS code to be conformed to Leaflet Routing API documentation.

* Add required model field `Route.vehicle` (default to "cycling"). When the user changes vehicle in leaflet JS, this field is updated in the backend.

* Change the vehicle icon in route overview corresponding to `Route.vehicle`: (driving/cycling/walking)
image

* Unit tests for SaveRouteView and SaveRouteVehicleView.

### Status

- [x] READY
- [ ] HOLD
- [ ] WIP (Work-In-Progress)

### How to verify this change

Set up kitchen count with a few geolocalized clients. At the last step "Organize Routes", it should be functional. The route should change when changing the vehicle. Then go back to "Route overview", the vehicle icon should be changed. Then go to django admin, find the route, the "vehicle" field should be changed.

### Deployment notes and migration

 - [x] DB Migration is needed.

### New translatable strings

 - [x] included

### Additional notes

none

### CODE REVIEW

**Comment by manumilou** [comment]
@lingxiaoyang Can this routing option be displayed on the routes list ?

capture d ecran de 2017-01-06 10-55-59

**Comment by lingxiaoyang** [comment]
@manumilou  This can be an initial parameter for the routing. But this "bicycle" label is not clickable. Maybe replacing the "Organize" button as three dropdown options or three buttons?

Also, Semantic UI doesn't have an icon for walking...

**Comment by manumilou** [comment]
@lingxiaoyang We just need to see the right information in this list, not interacting with it. 
We'll figure something out for the walk icon.

**Comment by lingxiaoyang** [comment]
@manumilou  I see... does it mean that we also need to store how a route is organized, cycling/walking/driving, in the database?

**Comment by lingxiaoyang** [comment]
Found an icon request for walking in FontAwesome. Not sure what license it uses:

https://github.com/FortAwesome/Font-Awesome/issues/844

**Comment by manumilou** [comment]
We need to store the information.

**Comment by lingxiaoyang** [comment]
@manumilou I reworked this PR. Can you check again the "changes proposed in this pull request" and see if it is acceptable?

**Comment by lingxiaoyang** [comment]
@manumilou  Unit tests and translatable strings are added in e5d8162.

**Pull request merged**
