### PR TITLE
Use Semantic multiple search dropdown

### PR DESCRIPTION
**Pull request by manumilou**
### Changes proposed in this pull request:

* Uses Semantic UI multiple dropdown to select ingredients
* Allow main dish selection

### Status

- [ ] READY
- [ ] HOLD
- [X] WIP (Work-In-Progress)

@savoirfairelinux/mll

### CODE REVIEW

**Comment by manumilou** [comment]
Not functional yet but here is what look like the interface. 
capture d ecran de 2016-08-03 18-55-07

**Comment by lamontfr** [comment]
Hi Manu,

This is great. I made a PR this morning to fix issue 297 and also the
whole kitchen count steps for the demo, but using the old template.

I had not enough time to use your new template. I will be happy to
integrate it to the view tomorrow; it is much nicer than my template.

**Comment by lamontfr** [comment]
@manumilou 
I would like to finish this myself to learn how to use this widget.

I submitted PR https://github.com/savoirfairelinux/santropol-feast/pull/317 , after you have verified and merged it, let me know if you agree ?

**Comment by lamontfr** [comment]
@manumilou The page is fully functional now according to your specs. I still have to do the test cases.

**Pull request closed without merging**
