### PR TITLE
Refactor order items code

### LINKED ISSUE #471: Improve the way the order items are handled
### Expected Behaviour

It should be easy to create new orders from the web interface.
It should be easy to create new order items from the web interface.

### Actual Behaviour

It is complicated. Lot of conditional fields are always displayed. Prices are not always computed properly.

### PR DESCRIPTION
**Pull request by manumilou**
### Changes proposed in this pull request:

* Remove free_quantity attribute
* Refactor order creation code
* Simplify order creation form
* Improves unit tests

### Status

- [x] READY
- [ ] HOLD
- [ ] WIP (Work-In-Progress)

### Deployment notes and migration

- [X] Migration is needed for this change

Changes in Order and OrderItem models.

### New translatable strings

- [ ] If applicable, I have included updated .po files with new strings (see http://goo.gl/kfBO7N)

### CODE REVIEW

**Comment by manumilou** [comment]
@erozqba @lamontfr : could you review this PR ?

**Comment by manumilou** [comment]
@philippemouchel  This PR will be useful for you.

**Comment by erozqba** [comment]
@manumilou, as soon I find out some free time I will check this!

**Comment by philippemouchel** [comment]
@manumilou, you may fill Quantity filed for an order_item with 1 ?

**Pull request merged**
