### PR TITLE
Add gulp to manage static files in the project.

### LINKED ISSUE #384: Extract all inline JS from the templates
### Expected Behaviour

The Javascript should live in an assets directory. Inline JS should be avoided when possible, as it makes maintenance and code readibility harder.

### Actual Behaviour

A looot of inline JS.

### PR DESCRIPTION
**Pull request by erozqba**
*Fixes #384 #385 .*

### Changes proposed in this pull request:

* Add some frontend dependency tools to the project (NPM and GULP).
* Reorder all frontend files in the frontend directory.
* Remove inline JavaScript, refactoring of JavaScript code, and remove code duplication.
* Add minification and compression for static files.

### Status

- [X] READY

### CODE REVIEW

**Comment by erozqba** [comment]
@manumilou you need to tests this manually because there are not frontend test that runs in Travis. I have made a lot of refactoring and remove code duplication that was all around the template files. I have made some tests by myself, but it will be nice to have a double validation!

**Comment by manumilou** [comment]
@erozqba Yes I will make some tests

**Comment by erozqba** [comment]
@manumilou I will let you know when this will be ready to merge and made the tests, I need to find out what was wrong during the rebase, the front page is not displayed correctly. I just try it now and is a real mess, sorry.

**Comment by manumilou** [comment]
@erozqba The commit message is way too long. You should use maximum 80 characters for the title. Then the description can be longer.

**Comment by manumilou** [comment]
Yes, I see that :-). I am missing the left sidebar, and the font is extra small.
Do I need to rebuild the web docker ? Then commands to run ?

**Comment by erozqba** [comment]
Not really, because is all generated files. If you need to modify any CSS and JS files there are CONTRIBUTING.md file that explains how to do it in the frontend directory.

**Comment by erozqba** [comment]
@manumilou needs review and needs testing. Thanks a lot in advance!
Any suggestions/comments/critics are welcome.

**Comment by ssirois** [comment]
I have tested this branch locally on my box.

* Dropdown lists, date pickers, animations and the like from the semantic-ui framework work well.
* Clients and Orders Status can be changed
* Map widget points me to the proper location

Issue found :

When pressing *cancel* on the modal window that appears when attempting to change a Client's status or an Order status : the modal window always comes back and we are stuck in there.

**Comment by ssirois** [comment]
I don't see the "Add minification and compression for static files." in effect, on /static/js/sous-chef.js

Might be because I'm in *debug* mode?

**Comment by manumilou** [comment]
@erozqba Once you'd addressed @ssirois comment, and fix the conflicts (sorry :-)), I promise you this PR is the next to be merged!

**Comment by erozqba** [comment]
@manumilou You should at least test the billing changes that you have merged before because @ssirois  has not tested that and there is some javascript duplication that I have removed and added the other to frontend/js/billing.js

**Comment by manumilou** [comment]
Ok. I will do that later tonight.

Le 15 septembre 2016 20:25:40 HAE, Ernesto Rodriguez Ortiz <notifications@github.com> a écrit :
>@manumilou You should at least test the billing changes that you have
>merged before because @ssirois  has not tested that and there is some
>javascript duplication that I have removed and added the other to
>frontend/js/billing.js
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/savoirfairelinux/sous-chef/pull/419#issuecomment-247490551

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Pull request merged**
