### PR TITLE
fix497 Kitchen count page adjusted to new requirements

### LINKED ISSUE #497: Adjust Kitchen Count Report to Revised Requirements
### Expected Behaviour

(Requirements were revised with Jérémie Vienneau on 2016-10-18)
- Add header and logo (moved to #498)
- Remove "Clashing - Component" column (but keep this information in client restrictions for CM's use and for a future alert mechanism)
- Main part columns ordered as : Clashing ingredient, Qty‐Reg, Qty‐Lge, Client, Preparation, Restrictions
- After each "SUBTOTAL" for a "Clashing ingredient", insert a separator
- Highlight restrictions that are generic
- Remove lines after "Total specials"
- Increase font size when printing  (moved to #498)

### PR DESCRIPTION
**Pull request by lamontfr**
### Changes proposed in this pull request:

**commit 365d2b1 :**
* delivery kitchen_count.html : reordered special meals columns, removed clashing components column,  improved grouping of lines relating to the combinations of ingredients.
* delivery views.py : adjusted meal lines generation, added comments
* order models.py : adjusted queries and kitchen items generation

**commit 1f78465 :**
- delivery views.py : removed code for retrieving and sorting route sequence
- member models.py : removed Route.client_id_sequence field  (see migration) and code for saving and retrieving route sequence
- delivery sample_data.json : removed Route.client_id_sequence field

### Status

- [X] READY

### How to verify this change

Select Kitchen Count Report in the UI and perform steps 1, 2, 3, 4, 5.

### Deployment notes and migration

- [X] Migration is needed for this change (for commit 1f78465)

### CODE REVIEW

**Comment by ssirois** [comment]
Sorry, my commit also includes a "clean code" fix on an empty code block in a elseif.

**Comment by ssirois** [comment]
There is a style issue as illustrated by following image:

attached document

This is due to the following rule in semantic.min.css:11
```

.ui.celled.table tr td:first-child, .ui.celled.table tr th:first-child {
	border-left: none;
}
```

that is applied on `.celled tables`.

**Comment by ssirois** [comment]
The row separator (as illustrated by the following image) is only visual and shouldn't be created by an empty row with empty cells. The visual separation effect should be created by the stylesheet.

sous-chef-pr-499_group-row-separator

**Comment by ssirois** [comment]
@manumilou should I open two issues for my last two comments (https://github.com/savoirfairelinux/sous-chef/pull/499#issuecomment-259851634 and https://github.com/savoirfairelinux/sous-chef/pull/499#issuecomment-259853359) since I believe those two comments are not show breakers to merge this pull request.

**Comment by lamontfr** [comment]
I will create a new PR only for the contents of commit 365d2b1 and commit "Fix empty HTML cells" 	c9adef2. Please do not merge this PR.

**Comment by lamontfr** [comment]
Please use PR #511 instead.

**Pull request closed without merging**
