### PR TITLE
Fix #599

### LINKED ISSUE #599: The admin should be able to add a bill's delivery item at the route sheets step
### Expected Behaviour

When organizing a route sheet, the user should be able to specify that a client will receive a bill as well as his meals.

capture d ecran de 2016-12-21 06-23-47

Receiving a bill  = adding a new order item, of type _delivery_.

The information must appear on the printable version as well.

### Actual Behaviour

To add a bill's delivery, the user has to go to the order view, update it, add a new delivery type order item, then return to the kitchen count.

### PR DESCRIPTION
**Pull request by lingxiaoyang**
### Changes proposed in this pull request:

* Define model property `Order_item.is_a_client_bill` if it is labeled "delivery" with no meal components. (Note: in earlier version of code, in order batch creation, we have "delivery" as the default type of every item. It has been corrected to "meal_component")
* Define model property and setter `Order.includes_a_bill`.
* Modify frontend: add billing toggle in route sheet table (in print, just yes/no). Add JS interaction for this toggle and its API view in Django.
* Add unit tests for all three above.

### Status

- [x] READY
- [ ] HOLD wait PR~~~s #592 and~~~ #593 to be merged
- [ ] WIP (Work-In-Progress)

### How to verify this change

http://localhost:8000/delivery/route_sheet/1/

The "Bill" toggles should be visible. Go to order detail view, toggle "Bill", refresh order detail view, then we should observe the addition/deletion of "delivery" item ($0.00, non-billable, no meal_component).

http://localhost:8000/delivery/routes/?print=yes

The print view should show Bill status (yes/no).

### Deployment notes and migration

none

### New translatable strings

- [x] If applicable, I have included updated .po files with new strings (see http://goo.gl/kfBO7N)

### Additional notes

image

image

image

### CODE REVIEW

**Comment by lingxiaoyang** [comment]
@manumilou 

> which kind of delivery

I don't understand this - which kinds do we have?

**Comment by manumilou** [comment]
@lingxiaoyang That answers my question. As of now, a delivery has no type.

**Comment by lingxiaoyang** [comment]
@manumilou  Fixed in c97d694

image

**Comment by lingxiaoyang** [comment]
Changed to WIP - need to specify billing type according to last meeting.

**Comment by manumilou** [comment]
@lingxiaoyang What do you mean Billing type?

**Pull request merged**
